lora:
  r: 8
  alpha: 16
  dropout: 0.10
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
qlora:
  enabled: true
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: nf4
  bnb_4bit_compute_dtype: bfloat16
